# Generated by Django 5.1.4 on 2026-08-28 05:39

import apps.ingest.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0002_athlete_onboarding_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawFitFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.ingest.models.fit_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('size_bytes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='athletes.athlete')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'constraints': [models.UniqueConstraint(fields=('athlete', 'sha256'), name='uniq_athlete_fit_hash')],
            },
        ),
    ]
