# Generated by Django 5.1.4 on 2026-08-28 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_athlete_onboarding_complete'),
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField(db_index=True)),
                ('sleep_seconds', models.IntegerField(blank=True, null=True)),
                ('sleep_need_seconds', models.IntegerField(blank=True, null=True)),
                ('sleep_score', models.IntegerField(blank=True, null=True)),
                ('deep_sleep_seconds', models.IntegerField(blank=True, null=True)),
                ('rem_sleep_seconds', models.IntegerField(blank=True, null=True)),
                ('awake_seconds', models.IntegerField(blank=True, null=True)),
                ('sleep_start_local', models.DateTimeField(blank=True, null=True)),
                ('sleep_end_local', models.DateTimeField(blank=True, null=True)),
                ('hrv_overnight_avg', models.IntegerField(blank=True, null=True)),
                ('hrv_status', models.CharField(blank=True, max_length=24)),
                ('training_readiness', models.IntegerField(blank=True, null=True)),
                ('training_readiness_level', models.CharField(blank=True, max_length=32)),
                ('training_status', models.CharField(blank=True, max_length=40)),
                ('acute_load', models.FloatField(blank=True, null=True)),
                ('chronic_load', models.FloatField(blank=True, null=True)),
                ('resting_hr', models.IntegerField(blank=True, null=True)),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('stress_avg', models.IntegerField(blank=True, null=True)),
                ('body_battery_high', models.IntegerField(blank=True, null=True)),
                ('body_battery_low', models.IntegerField(blank=True, null=True)),
                ('floors_climbed', models.IntegerField(blank=True, null=True)),
                ('intensity_minutes', models.IntegerField(blank=True, null=True)),
                ('spo2_avg', models.IntegerField(blank=True, null=True)),
                ('respiration_avg', models.FloatField(blank=True, null=True)),
                ('vo2max', models.FloatField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='athletes.athlete')),
            ],
            options={
                'verbose_name_plural': 'daily metrics',
                'ordering': ['-metric_date'],
                'constraints': [models.UniqueConstraint(fields=('athlete', 'metric_date'), name='uniq_athlete_metric_date')],
            },
        ),
    ]
