# Generated by Django 5.1.4 on 2026-08-28 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0003_activitymetrics_segment'),
        ('athletes', '0002_athlete_onboarding_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(db_index=True, max_length=40)),
                ('provider', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=60)),
                ('prompt_version', models.CharField(max_length=20)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('cached', 'Cached'), ('invalid', 'Failed validation'), ('refused', 'Refused by safety gate'), ('error', 'Error')], max_length=10)),
                ('retry_count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to='athletes.athlete')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('run', 'Run analysis'), ('weekly', 'Weekly review'), ('guidance', 'Coaching guidance'), ('journal', 'Journal extraction')], db_index=True, max_length=12)),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('prompt_version', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=60)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='activities.activity')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='athletes.athlete')),
            ],
            options={
                'verbose_name_plural': 'AI analyses',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('athlete', 'kind', 'input_hash'), name='uniq_athlete_kind_hash')],
            },
        ),
    ]
