# Generated by Django 5.1.4 on 2026-08-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='findings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
