# Generated by Django 5.1.4 on 2026-08-28 05:17

import apps.athletes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, help_text='Scales hydration and fuelling figures later.', null=True)),
                ('resting_hr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_hr', models.PositiveSmallIntegerField(blank=True, help_text='Observed max, not a 220-age formula estimate.', null=True)),
                ('easy_pace_min', models.PositiveSmallIntegerField(default=600, help_text='Fast edge of the easy band, sec/km. 600 = 10:00/km.')),
                ('easy_pace_max', models.PositiveSmallIntegerField(default=645, help_text='Slow edge of the easy band, sec/km. 645 = 10:45/km.')),
                ('hr_easy_min', models.PositiveSmallIntegerField(default=130)),
                ('hr_easy_max', models.PositiveSmallIntegerField(default=145)),
                ('hr_ceiling', models.PositiveSmallIntegerField(default=155, help_text='Cross this during a run block and the athlete should walk.')),
                ('run_cadence_threshold', models.PositiveSmallIntegerField(default=140, help_text='Cadence at or above this counts as running, not walking.')),
                ('available_days', models.JSONField(default=apps.athletes.models.default_available_days)),
                ('long_run_day', models.PositiveSmallIntegerField(default=6, help_text='0 = Monday. The one day with time for a long session.')),
                ('garmin_connected', models.BooleanField(default=False)),
                ('garmin_last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
