# Generated by Django 5.1.4 on 2026-08-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
