# Generated by Django 5.1.4 on 2026-08-28 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0002_athlete_onboarding_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_s', models.FloatField(help_text='Seconds since activity start.')),
                ('distance_m', models.FloatField(null=True)),
                ('speed_mps', models.FloatField(null=True)),
                ('cadence_spm', models.FloatField(help_text='Full steps/min, both legs.', null=True)),
                ('heart_rate', models.PositiveSmallIntegerField(null=True)),
                ('altitude_m', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('power_w', models.FloatField(null=True)),
                ('vertical_oscillation_mm', models.FloatField(null=True)),
                ('ground_contact_ms', models.FloatField(null=True)),
                ('stride_length_m', models.FloatField(null=True)),
                ('vertical_ratio', models.FloatField(null=True)),
                ('respiration_rate', models.FloatField(null=True)),
                ('temperature_c', models.FloatField(null=True)),
            ],
            options={
                'ordering': ['offset_s'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garmin_activity_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('source', models.CharField(choices=[('garmin_sync', 'Garmin sync'), ('fit_upload', 'Manual FIT upload')], max_length=20)),
                ('sport', models.CharField(default='running', max_length=40)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('local_date', models.DateField(db_index=True, help_text="Calendar date in the athlete's own timezone.")),
                ('total_distance_m', models.FloatField(default=0)),
                ('total_timer_s', models.FloatField(default=0)),
                ('total_elapsed_s', models.FloatField(default=0)),
                ('avg_hr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_hr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('avg_cadence_spm', models.FloatField(blank=True, null=True)),
                ('total_ascent_m', models.FloatField(blank=True, null=True)),
                ('total_descent_m', models.FloatField(blank=True, null=True)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('segmentation_version', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='athletes.athlete')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-started_at'],
            },
        ),
    ]
