# Generated by Django 5.1.4 on 2026-08-28 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='raw_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='ingest.rawfitfile'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='activities.activity'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(condition=models.Q(('garmin_activity_id__isnull', False)), fields=('athlete', 'garmin_activity_id'), name='uniq_athlete_garmin_activity'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['activity', 'offset_s'], name='activities__activit_19d7e8_idx'),
        ),
    ]
