# Generated by Django 5.1.4 on 2026-08-28 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_distance_m', models.FloatField()),
                ('walk_distance_m', models.FloatField()),
                ('run_fraction', models.FloatField()),
                ('run_duration_s', models.FloatField()),
                ('walk_duration_s', models.FloatField()),
                ('stop_duration_s', models.FloatField()),
                ('run_block_count', models.PositiveSmallIntegerField()),
                ('longest_run_m', models.FloatField()),
                ('longest_run_s', models.FloatField()),
                ('run_pace_s_per_km', models.FloatField(blank=True, null=True)),
                ('walk_pace_s_per_km', models.FloatField(blank=True, null=True)),
                ('blended_pace_s_per_km', models.FloatField(blank=True, null=True)),
                ('avg_run_cadence_spm', models.FloatField(blank=True, null=True)),
                ('avg_run_hr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hr_drift_percent', models.FloatField(blank=True, null=True)),
                ('custom_load', models.FloatField(blank=True, null=True)),
                ('load_formula_version', models.CharField(blank=True, max_length=8)),
                ('algorithm_version', models.IntegerField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='activities.activity')),
            ],
            options={
                'verbose_name_plural': 'activity metrics',
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('run', 'Run'), ('walk', 'Walk'), ('stop', 'Stop')], db_index=True, max_length=8)),
                ('start_offset_s', models.FloatField()),
                ('duration_s', models.FloatField()),
                ('distance_m', models.FloatField()),
                ('avg_pace_s_per_km', models.FloatField(blank=True, null=True)),
                ('avg_cadence_spm', models.FloatField(blank=True, null=True)),
                ('hr_start', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hr_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hr_avg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hr_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hr_recovery_60s', models.SmallIntegerField(blank=True, null=True)),
                ('hr_overshoot_bpm', models.SmallIntegerField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='activities.activity')),
            ],
            options={
                'ordering': ['activity', 'index'],
                'constraints': [models.UniqueConstraint(fields=('activity', 'index'), name='uniq_activity_segment_index')],
            },
        ),
    ]
