# Generated by Django 5.1.4 on 2026-08-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activitymetrics_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymetrics',
            name='time_in_zone',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
