# Generated by Django 5.1.4 on 2026-08-28 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0003_activitymetrics_segment'),
        ('athletes', '0002_athlete_onboarding_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('source', models.CharField(choices=[('chat', 'Chat'), ('run_log', 'Post-run log')], default='chat', max_length=10)),
                ('written_on', models.DateField(db_index=True)),
                ('applies_to_date', models.DateField(db_index=True)),
                ('extracted', models.JSONField(blank=True, null=True)),
                ('extraction_failed', models.BooleanField(default=False)),
                ('pain_reported', models.BooleanField(db_index=True, default=False)),
                ('illness_reported', models.BooleanField(db_index=True, default=False)),
                ('rpe', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reply', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='activities.activity')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='athletes.athlete')),
            ],
            options={
                'verbose_name_plural': 'journal entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
